package com.tzrcb.dispatch.model.table.dispatch.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDispatchRecord<M extends BaseDispatchRecord<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setTransNo(java.lang.String transNo) {
		set("trans_no", transNo);
	}
	
	public java.lang.String getTransNo() {
		return getStr("trans_no");
	}

	public void setSerno(java.lang.String serno) {
		set("serno", serno);
	}
	
	public java.lang.String getSerno() {
		return getStr("serno");
	}

	public void setSource(java.lang.String source) {
		set("source", source);
	}
	
	public java.lang.String getSource() {
		return getStr("source");
	}

	public void setTarget(java.lang.String target) {
		set("target", target);
	}
	
	public java.lang.String getTarget() {
		return getStr("target");
	}

	public void setVersion(java.lang.String version) {
		set("version", version);
	}
	
	public java.lang.String getVersion() {
		return getStr("version");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}

	public void setMessage(java.lang.String message) {
		set("message", message);
	}
	
	public java.lang.String getMessage() {
		return getStr("message");
	}

	public void setRequestMsg(java.lang.String requestMsg) {
		set("request_msg", requestMsg);
	}
	
	public java.lang.String getRequestMsg() {
		return getStr("request_msg");
	}

	public void setResponseMsg(java.lang.String responseMsg) {
		set("response_msg", responseMsg);
	}
	
	public java.lang.String getResponseMsg() {
		return getStr("response_msg");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}
	
	public java.lang.String getCreateTime() {
		return getStr("create_time");
	}

	public void setUpdateTime(java.lang.String updateTime) {
		set("update_time", updateTime);
	}
	
	public java.lang.String getUpdateTime() {
		return getStr("update_time");
	}

}
