package com.tzrcb.dispatch.model.table.dispatch.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseServiceConfig<M extends BaseServiceConfig<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setAppName(java.lang.String appName) {
		set("app_name", appName);
	}
	
	public java.lang.String getAppName() {
		return getStr("app_name");
	}

	public void setAppNo(java.lang.String appNo) {
		set("app_no", appNo);
	}
	
	public java.lang.String getAppNo() {
		return getStr("app_no");
	}

	public void setRouteNo(java.lang.String routeNo) {
		set("route_no", routeNo);
	}
	
	public java.lang.String getRouteNo() {
		return getStr("route_no");
	}

	public void setLicense(java.lang.String license) {
		set("license", license);
	}
	
	public java.lang.String getLicense() {
		return getStr("license");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}
	
	public java.lang.String getCreateTime() {
		return getStr("create_time");
	}

}
