package com.tzrcb.dispatch.model.table.dispatch;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _DbMappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _DbMappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("T_DISPATCH_RECORD", "id", DispatchRecord.class);
		arp.addMapping("T_ROUTE_CONFIG", "id", RouteConfig.class);
		arp.addMapping("T_SERVICE_CONFIG", "id", ServiceConfig.class);
		arp.addMapping("T_SMS_RECORD", "id", SmsRecord.class);
	}
}

