package com.tzrcb.dispatch.model.table.dispatch;

import com.tzrcb.dispatch.model.table.dispatch.base.BaseDispatchRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DispatchRecord extends BaseDispatchRecord<DispatchRecord> {
	public static final DispatchRecord dao = new DispatchRecord().dao();
}
