package com.tzrcb.dispatch.model.table.dispatch;

import com.tzrcb.dispatch.model.table.dispatch.base.BaseRouteConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RouteConfig extends BaseRouteConfig<RouteConfig> {
	public static final RouteConfig dao = new RouteConfig().dao();
}
