package com.tzrcb.dispatch.model.table.dispatch;

import com.tzrcb.dispatch.model.table.dispatch.base.BaseServiceConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ServiceConfig extends BaseServiceConfig<ServiceConfig> {
	public static final ServiceConfig dao = new ServiceConfig().dao();
}
