package com.tzrcb.dispatch.model.table.dispatch;

import com.tzrcb.dispatch.model.table.dispatch.base.BaseSmsRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmsRecord extends BaseSmsRecord<SmsRecord> {
	public static final SmsRecord dao = new SmsRecord().dao();
}
